name: Shoppy CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Build & Tests
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      APP_DEBUG: 1
      SYMFONY_DEPRECATIONS_HELPER: disabled

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: database
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          TZ: Europe/Paris
        ports:
          - 3318:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: composer:v2, flex, pcov
          coverage: pcov

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install vendors
        run: composer install --no-progress --ansi --no-scripts

      - name: Validate composer
        run: composer validate --no-check-lock

      - name: Warmup cache
        run: bin/console cache:warmup

      - name: Run PHPStan
        run: composer phpstan

      - name: Run PHPUnit tests
        run: composer test
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ tests ]
    concurrency: ${{ github.ref }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Deploy master
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: deployphp/action@v1
        with:
          deployer-version: "7.0.0-rc.3"
          private-key: ${{ secrets.PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy master

      - name: Deploy staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        uses: deployphp/action@v1
        with:
          deployer-version: "7.0.0-rc.3"
          private-key: ${{ secrets.PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy staging

      - name: Deploy dev
        if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/staging' }}
        uses: deployphp/action@v1
        with:
          deployer-version: "7.0.0-rc.3"
          private-key: ${{ secrets.DEV_PRIVATE_KEY }}
          known-hosts: ${{ secrets.GH_KNOWN_HOSTS }}
          dep: deploy dev
